[WIP] Repository skeleton
ezsystems/hybrid-platform-ui-core-components pull request #1
Opened 2017-04-14 14:15 UTC by dpobel

2017-04-18 16:09 UTC, dpobel commented on .travis.yml
> +node_js: stable
self note: consider using .nvmrc instead

2017-04-18 16:10 UTC, dpobel commented on README.md
> +* \<ez-toolbar\>
self note: add system requirements and how to run unit test and linting

2017-04-19 07:17 UTC, bdunogier commented on .eslintrc.json
> +{
You had fun writing this, had you not ? :)

2017-04-19 07:19 UTC, bdunogier requested changes
Minor details, besides that, +1.

2017-04-19 07:19 UTC, bdunogier commented on README.md
> +* \<ez-platform-ui-app\>
monospace font ?

2017-04-19 07:19 UTC, bdunogier commented on composer.json
> +    "license": "GPL-v2",
The syntax is `GPL-2.0` on our other repositories, for what it's worth.

2017-04-19 07:27 UTC, dpobel commented on .eslintrc.json
> +{
lol it was more or less auto-generated from PlatformUIBundle code base actually :)

2017-04-19 11:44 UTC, andrerom commented
>  any opinion on that ?

I agree, and if eslint is now the norm it makes sense to rather use that then jslint/jshint.

2017-04-24 12:11 UTC, dpobel commented
For now, I think we'll keep on using a standard close to what we were writing PlatformUIBundle with one exception due to the use of ES6 `const`. So instead of writing something like:

```js
var foo,
    bar,
    CONSTANT_FOO = 'foo',
    CONSTANT_BAR = 'bar';
```

we'll now use:

```
let foo;
let bar;
const CONSTANT_FOO = 'foo';
const CONSTANT_BAR = 'bar';
```

so basically, several `const` / `let` should be used.
Reasoning:
* this still guarantee to generate a minimal diff in case of change
* this avoids weird indentation when defining several constant with `const`

(gentle reminder ping @StephaneDiot @yannickroger)

2017-04-25 12:46 UTC, merged

2017-04-25 14:26 UTC, yannickroger commented
Quick comment to say I had a (late) look at it and it is great.