WIP EZP-27352: App should handle content discover event
ezsystems/hybrid-platform-ui-core-components pull request #16
Opened 2017-06-12 14:54 UTC by StephaneDiot

jira: https://jira.ez.no/browse/EZP-27352

## Description 

The app componenet should be responsible of handling the content discover event (event thaht launch UDW)

## todo

unit tests

2017-06-14 14:25 UTC, dpobel requested changes

2017-06-14 14:25 UTC, dpobel commented on js/ez-platform-ui-app.js
> +         * Adds event listener for 'contentDiscover' event.
`ez:contentDiscover` actually (with backticks instead of simple quotes)

2017-06-14 14:25 UTC, dpobel commented on js/ez-platform-ui-app.js
> +         *
CS

2017-06-14 14:25 UTC, dpobel commented on js/ez-platform-ui-app.js
> +                const {config, handlers} = e.detail;
this is a quite long and non trivial function, it deserves to be a named method and to have a short doc to explain what it does

2017-06-14 14:25 UTC, dpobel commented on js/ez-platform-ui-app.js
> +                document.body.appendChild(udw);
since the app is now responsible for creating the `<ez-universal-discovery>` element, it should be created inside the app not as a sibling element under body (and that's also why the `ez-js-standard-form` is needed on the `<ez-universal-discovery>`, while if it was created directly under the body, this class would not be necessary)

2017-06-14 14:25 UTC, dpobel commented on test/js/ez-platform-ui-app.js
> +            if (document.querySelector('ez-universal-discovery')) {
please use a local variable to avoid calling `document.querySelector('ez-universal-discovery')` 3 times in 2 lines

2017-06-14 14:25 UTC, dpobel commented on test/js/ez-platform-ui-app.js
> +    describe('handle contentDiscover', function () {
```js
describe('handle `ez:contentDiscover`', function () {
```

2017-06-16 10:40 UTC, bdunogier reviewed
I know that there are historical reasons why you name those things handlers, but it's still a very very generic name :)

2017-06-16 10:40 UTC, bdunogier commented on test/js/ez-platform-ui-app.js
> +                    handlers: {
Why `handlers` ? Aren't they used as `listeners` ?

2017-06-16 10:40 UTC, bdunogier commented on test/js/ez-platform-ui-app.js
> +        it('should set the handlers to the universal discovery widget', function () {
I'd rephrase this a bit (setting XXX to the UDW doesn't sound right). What about `should register the provided handlers as universal discovery widget listeners` ? It describes what is done better I think.

Sorry if I'm off-topic :)

2017-06-19 09:29 UTC, StephaneDiot commented on test/js/ez-platform-ui-app.js
> +                    handlers: {
actually here it's the struct of the detail attr I get from the event facade. To change this struct I need to alter some code out of this repo I guess...

2017-06-19 14:45 UTC, dpobel commented on test/js/ez-platform-ui-app.js
> +                    handlers: {
@StephaneDiot  Bertrand is right and it's the right time to change that

2017-06-19 14:51 UTC, dpobel requested changes

2017-06-19 14:51 UTC, dpobel commented on js/ez-platform-ui-app.js
> +            this.addEventListener('ez:contentDiscover', this._createUDCustomElement);
I think you need to bind this method to `this`

2017-06-19 14:52 UTC, dpobel commented on test/js/ez-platform-ui-app.js
> +                    handlers: {
note that at the moment, only `ez-browse` uses the UD and you are working on it :)

2017-06-20 14:17 UTC, StephaneDiot commented on test/js/ez-platform-ui-app.js
> +                    handlers: {
I agree with the change but  shouldn't this  be done with the implementation of <ez-browse> then ?

2017-06-21 09:55 UTC, dpobel commented on test/js/ez-platform-ui-app.js
> +                    handlers: {
as long as it's not forgotten, that works for me

2017-06-22 11:11 UTC, dpobel approved these changes

2017-06-22 11:47 UTC, merged